{% set name = "gwlearn" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwlearn-{{ version }}.tar.gz
  sha256: a125d559f9a38f8285b80dd1c8d89225f9c1bce87874ff25f8312af2e35d0a66

build:
  skip: true # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - geopandas >=1.0.0
    - joblib >=1.4.0
    - libpysal >=4.12
    - numpy >=1.26.0
    - scipy >=1.12.0
    - scikit-learn >=1.4.0
    - pandas >=2.1.0

test:
  imports:
    - gwlearn
  source_files:
    - gwlearn/tests
  commands:
    - pip check
    - pytest gwlearn/tests -v
  requires:
    - pip
    - pytest
    - geodatasets

about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Geographically weighted modelling based on scikit-learn
  description: |
    gwlearn provides a framework for prototyping geographically weighted extensions of regression
    and classification models based on scikit-learn and libpysal.graph and a subset of models
    implemented on top of this framework. For example, you can run geographically weighted
    linear regression in a following manner.
  dev_url: https://github.com/pysal/gwlearn
  doc_url: https://github.com/pysal/gwlearn/blob/main/README.md

extra:
  recipe-maintainers:
    - martinfleis
    - jGaboardi
